extraction:
  java:
    index:
      maven:
        settings_file: .build.settings.xml
    after_prepare:
      # Disable modules web and job because of node dependency in web and the ad-hoc nature of jobs
      - sed -i -e '/\s*<module>waltz-\(web\|jobs\)<\/module>/d' pom.xml
