dist: trusty

language:
  - java


jdk: openjdk8


env:
  global:
    - NODE_VERSION="7"


# Stop travis from running mvn install (without profile)
install: true


before_install:
  - nvm install $NODE_VERSION
  - npm install npm -g


# Enable caching of dependencies
cache:
  directories:
    - $HOME/.m2
    - node_modules

    
# safelist
branches:
  only:
    - master
    - rel.*
    - /^waltz-.*$/


jobs:
  include:
    - stage: Test
      env: DB=h2
      script:
        - mvn -s .build.settings.xml -Pbuild-h2 clean package;
        - npm run-script test --prefix ./waltz-ng
        -

    - stage: Test
      env: DB=postgres
      services:
        - postgresql
      before_script:
        - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS waltz;' -U postgres; fi"
        - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE waltz;' -U postgres; fi"
      script:
        - mvn -s .build.settings.xml -Pbuild-postgres clean package;
        - npm run-script test --prefix ./waltz-ng


    - stage: Test
      env: DB=mariadb
      addons:
        mariadb: 10.4
      before_script:
        - mysql -e "DROP DATABASE IF EXISTS waltz";
        - mysql -e "CREATE DATABASE IF NOT EXISTS waltz CHARACTER SET='utf8'";

      script:
        - mvn -s .build.settings.xml -Pbuild-mariadb clean package;
        - npm run-script test --prefix ./waltz-ng