language:
  - java

jdk: openjdk8

env:
  - NODE_VERSION="7"

script:
  - mvn -s .lgtm.settings.xml  clean package
  - npm run-script test --prefix ./waltz-ng

addons:
#  mariadb: '10.1'
#  apt:
#    packages:
#      - open-java8-installer

# Stop travis from running mvn install (without profile)
install: true

before_install:
#  - mysql -u root -e "create database IF NOT EXISTS waltz CHARACTER SET='utf8';"
  - nvm install $NODE_VERSION
  - npm install npm -g

# Enable caching of dependencies
cache:
  directories:
    - $HOME/.m2
    - node_modules
    
# safelist
branches:
  only:
    - master
    - rel.*
    - /^waltz-.*$/
